services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - "8000"

    env_file:
      - .env

    environment:
      - PYTHONUNBUFFERED=1

    command: ["poetry", "run", "uvicorn", "--host", "0.0.0.0", "--port", "8000", "app.app:app"]

    restart: always

  nginx:
    image: nginx:latest

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - app

    restart: always