services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["poetry", "run", "uvicorn", "--host", "0.0.0.0", "--port", "8000", "app.app:app"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # Porta HTTP
      - "443:443" # Porta HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Arquivo de configuração do Nginx
      - ./certs:/etc/nginx/certs  # Mapeamento dos certificados
    depends_on:
      - app
    restart: always
