"""add locator and auto generate ulids

Revision ID: 7a505457ae46
Revises: 48ec081a2154
Create Date: 2024-10-26 02:22:55.742756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a505457ae46'
down_revision: Union[str, None] = '48ec081a2154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('locator', sa.String(), nullable=False))
    op.create_index(op.f('ix_bookings_locator'), 'bookings', ['locator'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_locator'), table_name='bookings')
    op.drop_column('bookings', 'locator')
    # ### end Alembic commands ###
