"""create tables

Revision ID: 71ca64ab41c3
Revises:
Create Date: 2024-10-20 19:46:46.497866

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '71ca64ab41c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accommodations',
        sa.Column('ulid', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('AVAIABLE', 'OCUPIED', name='accommodationstatus'),
            nullable=False,
        ),
        sa.Column('total_guests', sa.Integer(), nullable=False),
        sa.Column('single_beds', sa.Integer(), nullable=False),
        sa.Column('double_beds', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('ulid'),
    )
    op.create_index(
        op.f('ix_accommodations_name'), 'accommodations', ['name'], unique=True
    )
    op.create_table(
        'amenities',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_amenities_name'), 'amenities', ['name'], unique=False
    )
    op.create_table(
        'guests',
        sa.Column('ulid', sa.String(), nullable=False),
        sa.Column('document', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('surname', sa.String(), nullable=False),
        sa.Column('country', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('ulid'),
    )
    op.create_index(
        op.f('ix_guests_document'), 'guests', ['document'], unique=True
    )
    op.create_table(
        'users',
        sa.Column('ulid', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column(
            'role',
            sa.Enum('ADMIN', 'USER', 'GUEST', name='role'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('ulid'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table(
        'amenities_per_accommodation',
        sa.Column('accommodation_ulid', sa.String(), nullable=True),
        sa.Column('amenitie_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['accommodation_ulid'], ['accommodations.ulid'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['amenitie_id'], ['amenities.id'], ondelete='CASCADE'
        ),
    )
    op.create_table(
        'bookings',
        sa.Column('ulid', sa.String(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'BOOKED',
                'WAITING_CHECK_IN',
                'ACTIVE',
                'WAITING_CHECK_OUT',
                'COMPLETED',
                'CANCELED',
                name='bookingstatus',
            ),
            nullable=False,
        ),
        sa.Column('check_in', sa.DateTime(), nullable=False),
        sa.Column('check_out', sa.DateTime(), nullable=False),
        sa.Column('budget', sa.Float(), nullable=False),
        sa.Column('guest_ulid', sa.String(), nullable=False),
        sa.Column('accommodation_ulid', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['accommodation_ulid'],
            ['accommodations.ulid'],
            ondelete='RESTRICT',
        ),
        sa.ForeignKeyConstraint(
            ['guest_ulid'], ['guests.ulid'], ondelete='RESTRICT'
        ),
        sa.PrimaryKeyConstraint('ulid'),
    )
    op.create_index(
        op.f('ix_bookings_check_in'), 'bookings', ['check_in'], unique=False
    )
    op.create_index(
        op.f('ix_bookings_check_out'), 'bookings', ['check_out'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_check_out'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_in'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('amenities_per_accommodation')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_guests_document'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_amenities_name'), table_name='amenities')
    op.drop_table('amenities')
    op.drop_index(op.f('ix_accommodations_name'), table_name='accommodations')
    op.drop_table('accommodations')
    # ### end Alembic commands ###
